#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:          ubtrosupgrade
# Required-Start:    $remote_fs $rc.local
# Required-Stop:     $remote_fs $rc.local
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: .
### END INIT INFO
case $1 in
    start)
        /usr/bin/rosupgrade &
        ;;
    stop)
        killall rosupgrade
        ;;
*)
echo "Usage: $0 (start|stop)"
;;
esac
